.TH man 8 "15 October 2019" "1.0" "course-wizard man page"
.SH NAME
course-wizzard \- Create a new course folder in the specified archive
.SH SYNOPSIS
couse-wizard arichve-directory
.SH DESCRIPTION
Will promt he user for information about the course, and will create that course
folder in archive-direcory. Then will ask the user if they want to create another
course.
.SH OPTIONS
The course-wizzard does not take any options.
.SH SEE ALSO
course-select
.SH BUGS
No known bugs.
.SH AUTHOR
Smauel Lando (samuel.lando@mail.concordia.ca)
