.TH man 8 "15 October 2019" "1.0" "course-select man page"
.SH NAME
course-select \- Symlink the desired course-wizzard course to specified location 
.SH SYNOPSIS
couse-select arichve-directory course-directory [selection]
.SH DESCRIPTION
Will symlink selection form archive-directory to course-directory, or list the 
possible selections if none is given.
.SH OPTIONS
The course-select does not take any options.
.SH SEE ALSO
course-wizard
.SH BUGS
No known bugs.
.SH AUTHOR
Smauel Lando (samuel.lando@mail.concordia.ca)
